--  创建数据库
create database kpl;
--  使用数据库
use kpl;
CREATE TABLE `alarms` (
                          `id` int NOT NULL AUTO_INCREMENT COMMENT '报警ID',
                          `alarm_item` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报警项',
                          `level` enum('low','medium','high','critical') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报警级别',
                          `device_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '关联设备ID',
                          `device_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '设备名称',
                          `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报警位置',
                          `alarm_time` datetime NOT NULL COMMENT '报警时间',
                          `resolve_time` datetime DEFAULT NULL COMMENT '解决时间',
                          `status` enum('pending','resolved') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'pending' COMMENT '报警状态',
                          `handle_notes` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '处理备注',
                          `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                          `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                          PRIMARY KEY (`id`) USING BTREE,
                          KEY `idx_alarm_time` (`alarm_time`) USING BTREE,
                          KEY `idx_status` (`status`) USING BTREE,
                          KEY `idx_level` (`level`) USING BTREE,
                          KEY `idx_device_id` (`device_id`) USING BTREE,
                          KEY `idx_level_alarm_time` (`level`,`alarm_time`) USING BTREE,
                          KEY `idx_status_alarm_time` (`status`,`alarm_time`) USING BTREE,
                          CONSTRAINT `fk_alarms_device_id` FOREIGN KEY (`device_id`) REFERENCES `devices` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                          CONSTRAINT `alarms_chk_1` CHECK ((`level` in (_utf8mb4'low',_utf8mb4'medium',_utf8mb4'high',_utf8mb4'critical'))),
                          CONSTRAINT `alarms_chk_2` CHECK ((`status` in (_utf8mb4'pending',_utf8mb4'resolved')))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='报警信息表';
CREATE TABLE `audit_logs` (
                              `id` int NOT NULL AUTO_INCREMENT COMMENT '日志ID',
                              `user_id` int DEFAULT NULL COMMENT '操作用户ID',
                              `action` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '操作类型',
                              `resource_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '资源类型',
                              `resource_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资源ID',
                              `ip_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '操作IP',
                              `user_agent` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户代理',
                              `details` json DEFAULT NULL COMMENT '操作详情',
                              `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                              PRIMARY KEY (`id`) USING BTREE,
                              KEY `idx_user_id` (`user_id`) USING BTREE,
                              KEY `idx_action` (`action`) USING BTREE,
                              KEY `idx_resource_type` (`resource_type`) USING BTREE,
                              KEY `idx_create_time` (`create_time`) USING BTREE,
                              CONSTRAINT `fk_audit_logs_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='审计日志表';
CREATE TABLE `devices` (
                           `id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '设备ID',
                           `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '设备名称',
                           `type_id` int DEFAULT '1' COMMENT '设备类型ID',
                           `model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备型号',
                           `serial_number` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备序列号',
                           `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备部署位置',
                           `status` enum('online','offline','maintenance','error') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'offline' COMMENT '设备状态',
                           `install_date` datetime DEFAULT NULL COMMENT '安装日期',
                           `last_maintenance` datetime DEFAULT NULL COMMENT '最后维护时间',
                           `next_maintenance` datetime DEFAULT NULL COMMENT '下次维护时间',
                           `last_heartbeat` datetime DEFAULT NULL COMMENT '最后心跳时间',
                           `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                           `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                           PRIMARY KEY (`id`) USING BTREE,
                           UNIQUE KEY `uk_serial_number` (`serial_number`) USING BTREE,
                           KEY `idx_status` (`status`) USING BTREE,
                           KEY `idx_type_id` (`type_id`) USING BTREE,
                           KEY `idx_location` (`location`) USING BTREE,
                           KEY `idx_update_time` (`update_time`) USING BTREE,
                           KEY `idx_status_location` (`status`,`location`) USING BTREE,
                           KEY `idx_devices_status` (`status`),
                           CONSTRAINT `devices_chk_1` CHECK ((`status` in (_utf8mb4'online',_utf8mb4'offline',_utf8mb4'maintenance',_utf8mb4'error')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='设备信息表';
CREATE TABLE `messages` (
                            `id` int NOT NULL AUTO_INCREMENT COMMENT '消息ID',
                            `user_id` int DEFAULT NULL COMMENT '接收用户ID',
                            `type` enum('system','alarm','notification','chat') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息类型',
                            `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息标题',
                            `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息内容',
                            `status` enum('unread','read') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'unread' COMMENT '消息状态',
                            `related_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '相关ID（如报警ID、设备ID等）',
                            `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                            `read_time` datetime DEFAULT NULL COMMENT '读取时间',
                            PRIMARY KEY (`id`) USING BTREE,
                            KEY `idx_user_id` (`user_id`) USING BTREE,
                            KEY `idx_type` (`type`) USING BTREE,
                            KEY `idx_status` (`status`) USING BTREE,
                            KEY `idx_create_time` (`create_time`) USING BTREE,
                            KEY `idx_user_status` (`user_id`,`status`) USING BTREE,
                            CONSTRAINT `fk_messages_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                            CONSTRAINT `messages_chk_1` CHECK ((`type` in (_utf8mb4'system',_utf8mb4'alarm',_utf8mb4'notification',_utf8mb4'chat'))),
                            CONSTRAINT `messages_chk_2` CHECK ((`status` in (_utf8mb4'unread',_utf8mb4'read')))
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='系统消息表';
CREATE TABLE `reports` (
                           `id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报告ID',
                           `type` enum('daily','weekly','monthly','custom') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报告类型',
                           `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '报告标题',
                           `start_date` date NOT NULL COMMENT '报告开始日期',
                           `end_date` date NOT NULL COMMENT '报告结束日期',
                           `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '报告内容',
                           `file_path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报告文件路径',
                           `status` enum('generating','completed','failed') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'generating' COMMENT '报告状态',
                           `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                           `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                           PRIMARY KEY (`id`) USING BTREE,
                           KEY `idx_type` (`type`) USING BTREE,
                           KEY `idx_status` (`status`) USING BTREE,
                           KEY `idx_date_range` (`start_date`,`end_date`) USING BTREE,
                           CONSTRAINT `reports_chk_1` CHECK ((`type` in (_utf8mb4'daily',_utf8mb4'weekly',_utf8mb4'monthly',_utf8mb4'custom'))),
                           CONSTRAINT `reports_chk_2` CHECK ((`status` in (_utf8mb4'generating',_utf8mb4'completed',_utf8mb4'failed')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='报告生成表';
CREATE TABLE `robots` (
                          `id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '机器人ID',
                          `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '机器人名称',
                          `type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '机器人类型',
                          `model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '机器人型号',
                          `location` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部署位置',
                          `manufacturer` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '生产厂商',
                          `install_date` datetime DEFAULT NULL COMMENT '安装日期',
                          `status` enum('online','offline','maintenance','error') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'offline' COMMENT '状态',
                          `battery` int DEFAULT '100' COMMENT '电池电量',
                          `last_heartbeat` datetime DEFAULT NULL COMMENT '最后心跳时间',
                          `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                          `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                          PRIMARY KEY (`id`) USING BTREE,
                          KEY `idx_name` (`name`) USING BTREE,
                          KEY `idx_type` (`type`) USING BTREE,
                          KEY `idx_status` (`status`) USING BTREE,
                          KEY `idx_location` (`location`) USING BTREE,
                          KEY `idx_update_time` (`update_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='机器人信息表';
CREATE TABLE `roles` (
                         `id` int NOT NULL AUTO_INCREMENT COMMENT '角色ID',
                         `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '角色名称',
                         `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '角色描述',
                         `permissions` json DEFAULT NULL COMMENT '角色权限',
                         `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                         `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                         PRIMARY KEY (`id`) USING BTREE,
                         UNIQUE KEY `uk_role_name` (`name`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='系统角色表';
CREATE TABLE `sensor_data` (
                               `id` int NOT NULL AUTO_INCREMENT,
                               `device_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '设备ID',
                               `type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '传感器类型',
                               `temperature` decimal(6,2) DEFAULT NULL COMMENT '温度',
                               `humidity` decimal(6,2) DEFAULT NULL COMMENT '湿度',
                               `smoke_level` decimal(6,2) DEFAULT NULL COMMENT '烟雾浓度',
                               `max_temp` json DEFAULT NULL COMMENT '最高温度',
                               `human_detected` tinyint(1) DEFAULT '0' COMMENT '是否检测到人',
                               `fire_risk` int DEFAULT '0' COMMENT '火灾风险等级',
                               `env_status` float DEFAULT '0' COMMENT '环境状态',
                               `battery` int DEFAULT '100' COMMENT '电池电量',
                               `record_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录时间',
                               `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                               PRIMARY KEY (`id`,`record_time`) USING BTREE,
                               KEY `idx_record_time` (`record_time`) USING BTREE,
                               KEY `idx_device_id` (`device_id`) USING BTREE,
                               KEY `idx_type` (`type`) USING BTREE,
                               KEY `idx_record_time_device` (`record_time`,`device_id`) USING BTREE,
                               KEY `idx_record_time_type` (`record_time`,`type`) USING BTREE,
                               KEY `idx_sensor_record_time` (`record_time`),
                               KEY `idx_sensor_device_id` (`device_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10219 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='传感器数据表';
CREATE TABLE `users` (
                         `id` int NOT NULL AUTO_INCREMENT COMMENT '用户ID',
                         `username` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户名',
                         `password_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '密码哈希',
                         `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机号',
                         `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '邮箱',
                         `role_id` int DEFAULT '1' COMMENT '关联角色ID',
                         `status` enum('active','inactive','locked') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'active' COMMENT '状态',
                         `login_count` int DEFAULT '0' COMMENT '登录次数',
                         `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
                         `last_login_ip` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最后登录IP',
                         `failed_login_attempts` int DEFAULT '0' COMMENT '失败登录尝试次数',
                         `lock_until` datetime DEFAULT NULL COMMENT '锁定时间',
                         `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                         `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                         PRIMARY KEY (`id`) USING BTREE,
                         UNIQUE KEY `uk_username` (`username`) USING BTREE,
                         UNIQUE KEY `uk_phone` (`phone`) USING BTREE,
                         UNIQUE KEY `uk_email` (`email`) USING BTREE,
                         KEY `idx_role_id` (`role_id`) USING BTREE,
                         KEY `idx_status` (`status`) USING BTREE,
                         KEY `idx_last_login_time` (`last_login_time`) USING BTREE,
                         KEY `idx_users_email` (`email`),
                         CONSTRAINT `fk_users_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=313 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='系统用户表';