const express = require('express');
const router = express.Router();
const { apiErrorHandler } = require('../../middlewares/apiHandler');
const authRouter = require('./auth');
const robotRouter = require('./robot');
const sseRouter = require('./sse');
const environmentRouter = require('./environment');
const alertsRouter = require('./alerts');
const devicesRouter = require('./devices');
const sensorsRouter = require('./sensors');
const messagesRouter = require('./messages');
const usersRouter = require('./users');
const systemRouter = require('./system');
const reportsRouter = require('./reports');
router.use('/auth', authRouter);
router.use('/robot', robotRouter);
router.use('/sse', sseRouter);
router.use('/environment', environmentRouter);
router.use('/alerts', alertsRouter);
router.use('/devices', devicesRouter);
router.use('/sensors', sensorsRouter);
router.use('/messages', messagesRouter);
router.use('/users', usersRouter);
router.use('/system', systemRouter);
router.use('/reports', reportsRouter);
router.use(apiErrorHandler);
module.exports = router;